### ISSUE TITLE
How does this compare to Gatsby incremental builds?

### ISSUE THREAD

**Issue by Vacilando** [jlengstorf/netlify-plugin-gatsby-cache#18]
Hi, how does this plugin compare to Gatsby's new incremental builds? See https://www.gatsbyjs.org/blog/2020-04-22-announcing-incremental-builds/

Are they trying to achieve the same and are exclusive of each other, or do they complement each other?

**Comment by jlengstorf** [comment]
this is a part of incremental builds

your timing is perfect, actually, because I just wrote a post showing [how to enable Gatsby incremental builds on Netlify](https://www.netlify.com/blog/2020/04/23/enable-gatsby-incremental-builds-on-netlify/?utm_source=github&utm_medium=gatsby-inc-builds-jl&utm_campaign=devex)! 

this plugin keeps the `public` and `.cache` folders around between builds, which Gatsby uses for incremental builds. there's also a flag that needs to be set and a minimum version of Gatsby required (I cover all that in the post), but all-in it takes 5 steps to implement and test it

I'm going to close this, but feel free to follow up with any questions!

**Comment by polarathene** [comment]
> this is a part of incremental builds

Is there a breakdown of what is required to achieve this functionality in a self-hosted manner?

So far I'm only aware of:

- This caching step (which I thought was a common optimization with CI services? I've done such with Travis for example).
- Distributed builds via a job-scheduler/work-queue [as described here](https://www.netlify.com/blog/2020/02/25/gatsby-build-speed-improvements-with-parallel-image-processing/) with `gatsby-parallel-runner` on GCP. Not specifically incremental, but can reduce build time.

Is there anything else going on, or by using this plugin and following your netlify article, you'd have the equivalent incremental build functionality Gatsby Cloud offers?

**Comment by jlengstorf** [comment]
@polarathene Gatsby hasn't really explained what happens (which makes sense, since they're positioning it as their product/competitive advantage and not part of the open source tool), so it's hard to do anything other than speculate right now

for any concrete breakdown, the Gatsby team would need to comment
