### ISSUE TITLE
This plugin is missing a "manifest.yml"

### ISSUE THREAD

**Issue by MZOG** [jlengstorf/netlify-plugin-gatsby-cache#29]
Hi,

I am getting this error when I try to deploy.

![Netlify issue](https://www.datocms-assets.com/26663/1590969068-dtb-2020-06-01-at-00-50-57.png?auto=format&ar=759%3A628&fit=max&ixlib=react-9.0.1&w=1074)

Does anyone had this before? 
About 20 days ago everything was ok.

**Comment by KarlRombauts** [comment]
I am experiencing the same issue. 

Everything seemed to be working on May 25th, and then the next build on May 27th failed due to a plugin error.

![image](https://user-images.githubusercontent.com/24811150/83367721-4e0ed300-a3f9-11ea-8be9-c03736bd3bb5.png)

My error message in the build log looks identical to yours. 

After some digging, I found that 7 days ago Netlify has required manifest.yml files. See this commit: https://github.com/netlify/build/commit/773d32bab879e2cab9fe94ec203f5621d1e87212

**Comment by KarlRombauts** [comment]
Interestingly, when I cleared my Netlify cache and tried rebuilding, everything went smoothly. 

![image](https://user-images.githubusercontent.com/24811150/83369271-23277d80-a3ff-11ea-83d9-3598ef6389ef.png)

But then I tried building again, now that the cache had been populated, Netlify threw the same error again. 
![image](https://user-images.githubusercontent.com/24811150/83369347-5f5ade00-a3ff-11ea-9005-5fda7d1ee141.png)

Admittedly I don't fully understand the Netlify cache and the details about what it stores. But maybe someone with more experience can shed some light on what is happening. :)

For now, I am just disabling the plugin, but if there is anything I can do to try and help fix the issue let me know. I really like this plugin as it makes my builds super snappy!

**Comment by jlengstorf** [comment]
hey, everyone! thanks for reporting this!

this issue is due to Netlify using the cached version of the plugin, which was missing a manifest prior to `v0.2.2`

the appropriate fix is to run a "clear cache and deploy" on Netlify, which will pull the latest version of the plugin

I'll look into a fix on the Netlify side to see if we can auto-retry for plugins with new versions or something — will report back if anything changes

in the meantime, I'm going to close this because the latest version of the plugin works, but please feel free to post additional questions here!
